<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MGTECHLPT311" failures="1" tests="3" name="TestClass.TC_009_EndToEnd_Test" time="6.210" errors="0" timestamp="2023-06-05T15:35:58 IST" skipped="0">
  <testcase classname="TestClass.TC_009_EndToEnd_Test" name="IndexPage_Test" time="1.553"/>
  <system-out/>
  <testcase classname="TestClass.TC_009_EndToEnd_Test" name="ProductSearchPage_Test" time="3.972"/>
  <system-out/>
  <testcase classname="TestClass.TC_009_EndToEnd_Test" name="ShopingCartPage_Test" time="0.685">
    <failure message="expected [400.0] but found [300.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400.0] but found [300.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at TestClass.TC_009_EndToEnd_Test.ShopingCartPage_Test(TC_009_EndToEnd_Test.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- ShopingCartPage_Test -->
  <system-out/>
</testsuite> <!-- TestClass.TC_009_EndToEnd_Test -->
